### PR TITLE
Fixes #541 compilation error

### LINKED ISSUE #541: Fails to compile with glibc 2.29/gcc 8+: src/os/unix/pws_time.h:17:18: error: conflicting declaration ‘typedef uint64_t __time_t’
Compiling with glibc version 2.29, gcc 8.2.0. Log of build failure attached.

[build-failure.log](https://github.com/pwsafe/pwsafe/files/2994587/build-failure.log)

### PR DESCRIPTION
**Pull request by Appleman1234**
Fixes #541 
Updates pws_time.h to check for existing definition of __time64_t before attempting to redefine it using a typedef.

### CODE REVIEW

**Comment by ronys** [comment]
Thanks!
