### ISSUE TITLE
pwsafe fails to build on 10.3-RELEASE-p5

### ISSUE THREAD

**Issue by derekschrock** [pwsafe/pwsafe#130]
With x11-toolkits/wxgtk30 and devel/gmake installed building pwsafe with the instructions from README.FREEBSD the build fails with the following error[s]:

$ NO_YUBI=1 gmake release
gmake unicoderelease
gmake[1]: Entering directory '/usr/home/dereks/repos/pwsafe'
gmake -C src/os/unix unicoderelease
gmake[2]: Entering directory '/usr/home/dereks/repos/pwsafe/src/os/unix'
In file included from UUID.cpp:16:
./../UUID.h:22:10: fatal error: 'uuid/uuid.h' file not found
#include <uuid/uuid.h> // aptitude install uuid-dev
         ^
1 error generated.
In file included from UUID.cpp:16:
./../UUID.h:22:10: fatal error: 'uuid/uuid.h' file not found
#include <uuid/uuid.h> // aptitude install uuid-dev
         ^
1 error generated.
gmake all CONFIG=unicoderelease
gmake[3]: Entering directory '/usr/home/dereks/repos/pwsafe/src/os/unix'
In file included from UUID.cpp:16:
./../UUID.h:22:10: fatal error: 'uuid/uuid.h' file not found
#include <uuid/uuid.h> // aptitude install uuid-dev
         ^
1 error generated.
clang++ --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  -std=c++11 -std=c++11 -O0 -g -ggdb -DUNICODE -DDEBUG -O -DUNICODE -DNDEBUG -c debug.cpp -o ../../../obj/unicoderelease/os/debug.o
clang++ --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  -std=c++11 -std=c++11 -O0 -g -ggdb -DUNICODE -DDEBUG -O -DUNICODE -DNDEBUG -c dir.cpp -o ../../../obj/unicoderelease/os/dir.o
clang++ --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  -std=c++11 -std=c++11 -O0 -g -ggdb -DUNICODE -DDEBUG -O -DUNICODE -DNDEBUG -c env.cpp -o ../../../obj/unicoderelease/os/env.o
clang++ --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  -std=c++11 -std=c++11 -O0 -g -ggdb -DUNICODE -DDEBUG -O -DUNICODE -DNDEBUG -c file.cpp -o ../../../obj/unicoderelease/os/file.o
clang++ --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  -std=c++11 -std=c++11 -O0 -g -ggdb -DUNICODE -DDEBUG -O -DUNICODE -DNDEBUG -c logit.cpp -o ../../../obj/unicoderelease/os/logit.o
clang++ --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  -std=c++11 -std=c++11 -O0 -g -ggdb -DUNICODE -DDEBUG -O -DUNICODE -DNDEBUG -c media.cpp -o ../../../obj/unicoderelease/os/media.o
clang++ --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  -std=c++11 -std=c++11 -O0 -g -ggdb -DUNICODE -DDEBUG -O -DUNICODE -DNDEBUG -c mem.cpp -o ../../../obj/unicoderelease/os/mem.o
clang++ --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  -std=c++11 -std=c++11 -O0 -g -ggdb -DUNICODE -DDEBUG -O -DUNICODE -DNDEBUG -c pws_str.cpp -o ../../../obj/unicoderelease/os/pws_str.o
clang++ --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  -std=c++11 -std=c++11 -O0 -g -ggdb -DUNICODE -DDEBUG -O -DUNICODE -DNDEBUG -c pws_time.cpp -o ../../../obj/unicoderelease/os/pws_time.o
clang++ --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  -std=c++11 -std=c++11 -O0 -g -ggdb -DUNICODE -DDEBUG -O -DUNICODE -DNDEBUG -c rand.cpp -o ../../../obj/unicoderelease/os/rand.o
clang++ --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  -std=c++11 -std=c++11 -O0 -g -ggdb -DUNICODE -DDEBUG -O -DUNICODE -DNDEBUG -c run.cpp -o ../../../obj/unicoderelease/os/run.o
clang++ --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  -std=c++11 -std=c++11 -O0 -g -ggdb -DUNICODE -DDEBUG -O -DUNICODE -DNDEBUG -c utf8conv.cpp -o ../../../obj/unicoderelease/os/utf8conv.o
clang++ --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  -std=c++11 -std=c++11 -O0 -g -ggdb -DUNICODE -DDEBUG -O -DUNICODE -DNDEBUG -c KeySend.cpp -o ../../../obj/unicoderelease/os/KeySend.o
KeySend.cpp:18:1: warning: 'PrefT' defined as a struct template here but previously declared as a class template [-Wmismatched-tags]
struct PrefT<PWSprefs::BoolPrefs> {
^
KeySend.cpp:15:1: note: did you mean struct here?
class PrefT;
^~~~~
struct
KeySend.cpp:23:1: warning: 'PrefT' defined as a struct template here but previously declared as a class template [-Wmismatched-tags]
struct PrefT<PWSprefs::IntPrefs> {
^
KeySend.cpp:15:1: note: did you mean struct here?
class PrefT;
^~~~~
struct
KeySend.cpp:28:1: warning: 'PrefT' defined as a struct template here but previously declared as a class template [-Wmismatched-tags]
struct PrefT<PWSprefs::StringPrefs> {
^
KeySend.cpp:15:1: note: did you mean struct here?
class PrefT;
^~~~~
struct
3 warnings generated.
clang++ --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  -std=c++11 -std=c++11 -O0 -g -ggdb -DUNICODE -DDEBUG -O -DUNICODE -DNDEBUG -c sleep.cpp -o ../../../obj/unicoderelease/os/sleep.o
clang++ --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  --stdlib=libc++ -I/usr/local/include --stdlib=libc++ -I/usr/local/include -fPIC -Wall -I../../core -I../.. `/usr/local/bin/wxgtk2u-3.0-config --debug=no --unicode=yes --inplace --cxxflags`  -std=c++11 -std=c++11 -O0 -g -ggdb -DUNICODE -DDEBUG -O -DUNICODE -DNDEBUG -c xsendstring.cpp -o ../../../obj/unicoderelease/os/xsendstring.o
Stack dump:
0.      Program arguments: /usr/bin/clang++ -cc1 -triple x86_64-unknown-freebsd10.3 -emit-obj -disable-free -disable-llvm-verifier -main-file-name xsendstring.cpp -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -gdwarf-2 -coverage-file /usr/home/dereks/repos/pwsafe/src/os/unix/../../../obj/unicoderelease/os/xsendstring.o -resource-dir /usr/bin/../lib/clang/3.4.1 -D _FILE_OFFSET_BITS=64 -D WXUSINGDLL -D __WXGTK__ -D _THREAD_SAFE -D _FILE_OFFSET_BITS=64 -D WXUSINGDLL -D __WXGTK__ -D _THREAD_SAFE -D UNICODE -D DEBUG -D UNICODE -D NDEBUG -I /usr/local/include -I /usr/local/include -I ../../core -I ../.. -I /usr/local/lib/wx/include/gtk2-unicode-3.0 -I /usr/local/include/wx-3.0 -I /usr/local/include -I /usr/local/include -I ../../core -I ../.. -I /usr/local/lib/wx/include/gtk2-unicode-3.0 -I /usr/local/include/wx-3.0 -internal-isystem /usr/include/c++/v1 -O2 -Wall -Wall -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /usr/home/dereks/repos/pwsafe/src/os/unix -ferror-limit 19 -fmessage-length 204 -pthread -mstackrealign -fobjc-runtime=gnustep -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o ../../../obj/unicoderelease/os/xsendstring.o -x c++ xsendstring.cpp
1.      <eof> parser at end of file
2.      Per-file LLVM IR generation
3.      xsendstring.cpp:428:5: Generating code for declaration 'ModifierFactory::ModifierCreator<unsigned long>::ModifierCreator'
clang++: error: unable to execute command: Segmentation fault (core dumped)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.3
Thread model: posix
clang++: note: diagnostic msg: PLEASE submit a bug report to https://bugs.freebsd.org/submit/ and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/xsendstring-1c725e.cpp
clang++: note: diagnostic msg: /tmp/xsendstring-1c725e.sh
clang++: note: diagnostic msg:

********************
gmake[3]: *** [Makefile:79: ../../../obj/unicoderelease/os/xsendstring.o] Error 254
gmake[3]: Leaving directory '/usr/home/dereks/repos/pwsafe/src/os/unix'
gmake[2]: *** [Makefile:84: unicoderelease] Error 2
gmake[2]: Leaving directory '/usr/home/dereks/repos/pwsafe/src/os/unix'
gmake[1]: *** [Makefile.freebsd:59: unicoderelease] Error 2
gmake[1]: Leaving directory '/usr/home/dereks/repos/pwsafe'
gmake: *** [Makefile.freebsd:68: release] Error 2

**Comment by derekschrock** [comment]
It's possible this is a clang 3.4 issue?  

However, with the attached patch I can get pwsafe to build on 10.3-RELEASE with lang/clang38.



[0001-Update-pwsafe-to-build-with-cmake-on-FreeBSD-10.3.txt](https://github.com/pwsafe/pwsafe/files/368101/0001-Update-pwsafe-to-build-with-cmake-on-FreeBSD-10.3.txt)

**Comment by ronys** [comment]
Hm.

A compiler crash is always an issue with the compiler, by definition.

Re your patch: are you sure the compiled program is under src/ui/wxWidgets/GCCUnicodeRelease when building with cmake? That's the location for the old Makefile-based build. Cmake's build should create the executable directly in the build directory (at least, that's what it does under Linux).

Can you create a pull request for your fix, or at least a patch that 'git am' will accept?

Thanks!

  Rony

**Comment by derekschrock** [comment]
Pull request created #131

**Comment by ronys** [comment]
Pull request reviewed and accepted, closing this based on submitter (haven't tried building on FreeBSD myself).
