### PR TITLE
Fixes Build failure on Mac OS X

### LINKED ISSUE #188: Build failure on Mac OS X 10.11.6 with Xcode 8.0
There are 2 problems to build on Mac OS X 10.11.6 with Xcode 8.0 and wxWindows 3.0.2 (also 3.1.0).

## 1. Linking error with libpng

```
Apple Mach-O Linker (ld) Error Group
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ld: library not found for -lpng
```

This can be fixed by adding `-L/usr/local/lib` to "pwsafe - Build Settings - Linking - Other Linker Flags" to use brewed libpng, because Mac OS X 10.11 may not bundle libpng itsself.

## 2. Another linking error

```
Apple Mach-O Linker (ld) Error Group
Undefined symbols for architecture x86_64:
  "CPasswordSubset::CPasswordSubset(wxWindow*, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, S_Alloc::SecureAlloc<wchar_t> > const&, int, wxString const&, wxPoint const&, wxSize const&, long)", referenced from:
      PasswordSafeFrame::DoPasswordSubset(CItemData&) in mainEdit.o
  "CPasswordSubset::~CPasswordSubset()", referenced from:
      PasswordSafeFrame::DoPasswordSubset(CItemData&) in mainEdit.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I don't know how to resolve this problem.

### PR DESCRIPTION
**Pull request by comutt**
This fixes #188

- Added '-L/usr/local/lib' to the linker flags
- Added 'passwordsubsets.{cpp,h}' to a Xcode project

### CODE REVIEW

**Comment by ronys** [comment]
Looks good - thanks!
