### ISSUE TITLE
Build failure on Mac OS X 10.11.6 with Xcode 8.0

### ISSUE THREAD

**Issue by comutt** [pwsafe/pwsafe#188]
There are 2 problems to build on Mac OS X 10.11.6 with Xcode 8.0 and wxWindows 3.0.2 (also 3.1.0).

## 1. Linking error with libpng

```
Apple Mach-O Linker (ld) Error Group
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ld: library not found for -lpng
```

This can be fixed by adding `-L/usr/local/lib` to "pwsafe - Build Settings - Linking - Other Linker Flags" to use brewed libpng, because Mac OS X 10.11 may not bundle libpng itsself.

## 2. Another linking error

```
Apple Mach-O Linker (ld) Error Group
Undefined symbols for architecture x86_64:
  "CPasswordSubset::CPasswordSubset(wxWindow*, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, S_Alloc::SecureAlloc<wchar_t> > const&, int, wxString const&, wxPoint const&, wxSize const&, long)", referenced from:
      PasswordSafeFrame::DoPasswordSubset(CItemData&) in mainEdit.o
  "CPasswordSubset::~CPasswordSubset()", referenced from:
      PasswordSafeFrame::DoPasswordSubset(CItemData&) in mainEdit.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I don't know how to resolve this problem.

**Comment by ronys** [comment]
Re the first problem, if you could add the flag for the Mac OS build into the toplevel CMakeLists.txt and/or the Makefile in src/ui/wxWidgets, that would be great.

Re the second one, it looks like you're missing the (relatively new) passwordsubset.cpp source file from your source code list in the IDE. This file is both in the Makefile and CMakeLists.txt, so I'd guess you're not using either for the build.

**Comment by comutt** [comment]
@ronys Thanks, I've created PR to fix this issue.

> Re the first problem, if you could add the flag for the Mac OS build into the toplevel CMakeLists.txt and/or the Makefile in src/ui/wxWidgets, that would be great.

I've added `-L/usr/local/lib` to `Xcode/generate-configs` that pwsafe provides.

> Re the second one, it looks like you're missing the (relatively new) passwordsubset.cpp source file from your source code list in the IDE. This file is both in the Makefile and CMakeLists.txt, so I'd guess you're not using either for the build.

I've added missing `wxWidgets/passwordsubset.{cpp,h}` to a Xcode project.
