### PR TITLE
Fix wx3.3 translation issues

### PR DESCRIPTION
**Pull request by sauravg**
See https://wxwidgets.org/help/msgid-literals/

### CODE REVIEW

**Review by dskrvk — APPROVED** [review]
Nice, looks like in most of these cases _() was unnecessary in the first place.

**Comment by dskrvk** [comment]
TIL: wxWidgets has [`wxPLURAL`](https://docs.wxwidgets.org/3.2.7/group__group__funcmacro__string.html#gadc7c2f1bab3914af93feb47945003409) which is the proper way to define multiple forms of plurals (this came up in a PR discussion recently).

Also https://www.gnu.org/software/gettext/manual/gettext.html#Plural-forms

File: src/core/StringX.cpp [hunk 1]
```diff
@@ -156,7 +156,7 @@ template<class T> void LoadAString(T &s, int id)
   cs.LoadString(id);
   s = cs;
 #else
-  s = _(core_st[id]).c_str();
+  s = core_st[id];
```
Comment (huven) [inline src/core/StringX.cpp]: If this is committed, then maybe also remove

#include <wx/intl.h>

from line 19? Looks like that include was only for this line. Saves me from making two edits on every update 😊

Comment (sauravg) [reply src/core/StringX.cpp]: Makes sense. Done in [eb86350](https://github.com/pwsafe/pwsafe/pull/1852/commits/eb8635000ffcd2b980644a769f7250f61ee9b828)

**Comment by nobugshere** [comment]
Back when I tried this in #1520, I received this comment:

> Looks like, that most of these changes should be reverted or implemented in other way. After these changes items in combo boxes in settings, messages in status bar, field names in dragbar tooltips, ... become untranslated.

I reverted the change and never got back to it.  It appears the same issues are present in this PR, at least when I build with wx3.2.10 on macOS.  Aparently some of these supposedly "unnecessary" uses of _() actually have an effect.

**Comment by froggie2523** [comment]
This is a breaking change - most, if not all the _("<variable_name>") strings are translated into the current application language at runtime using PO files.

**Comment by dskrvk** [comment]
The one change I'm not sure about is `FieldTypeString`: looking at the code, if we remove the translations around it, the strings are just passed as is to the UI. That said, I'm not sure how this could've worked before seeing as that map contains `wxString`s which aren't supposed to be translated.

**Comment by nobugshere** [comment]
I think what's needed is to, judiciously, replace _() with explicit calls to wxGetTranslation().  I did some quick experimentation, but had mixed results.
- Fixing the drag bar tool-tips by inserting wxGetTranslation() in DragBarCtrl.cpp where _() use to be seems to work
- Trying to fix the double-click/shift-double-click combo boxes in OptionsPropertySheetDlg.cpp the same way did not.

Clearly, I have much to learn about this process.

**Comment by ronys** [comment]
Non-Windows builds are now failing with:
```
2026-07-09T12:17:01.9824079Z /home/runner/work/pwsafe/pwsafe/src/ui/wxWidgets/GridCtrl.cpp: In member function ‘void GridCtrl::RearrangeItemsDateTimeBased(ItemsCollection&, int, bool)’:
2026-07-09T12:17:01.9827108Z /home/runner/work/pwsafe/pwsafe/src/ui/wxWidgets/GridCtrl.cpp:755:29: error: request for member ‘data’ in ‘datetime.wxString::wc_str()’, which is of non-class type ‘const wchar_t*’
2026-07-09T12:17:01.9829166Z   755 |           datetime.wc_str().data(), dt.GetDay(), dt.GetMonth(), dt.GetYear());
2026-07-09T12:17:01.9830033Z       |                             ^~~~
2026-07-09T12:17:01.9832289Z /home/runner/work/pwsafe/pwsafe/src/ui/wxWidgets/GridCtrl.cpp:759:96: error: request for member ‘data’ in ‘datetime.wxString::wc_str()’, which is of non-class type ‘const wchar_t*’
2026-07-09T12:17:01.9834561Z   759 |       pws_os::Trace(L"Failed to parse item's date string: %ls ; using: %ls", datetime.wc_str().data(), wxDateTime::Today().FormatISOCombined().wc_str().data());
2026-07-09T12:17:01.9836063Z       |                                                                                                ^~~~
2026-07-09T12:17:01.9838444Z /home/runner/work/pwsafe/pwsafe/src/ui/wxWidgets/GridCtrl.cpp:759:153: error: request for member ‘data’ in ‘wxDateTime::Today().wxDateTime::FormatISOCombined().wxString::wc_str()’, which is of non-class type ‘const wchar_t*’
2026-07-09T12:17:01.9841832Z   759 |       pws_os::Trace(L"Failed to parse item's date string: %ls ; using: %ls", datetime.wc_str().data(), wxDateTime::Today().FormatISOCombined().wc_str().data());
2026-07-09T12:17:01.9843407Z       |
```

File: src/ui/wxWidgets/wxUtilities.cpp [hunk 2]
```diff
@@ -227,7 +227,7 @@ SafeCombinationCtrl* wxUtilities::CreateLabeledSafeCombinationCtrl(wxWindow* par
   auto *sizer = new wxBoxSizer(wxVERTICAL);
   parent->GetSizer()->Add(sizer, 0, wxBOTTOM|wxLEFT|wxRIGHT|wxEXPAND, 12);
 
-  auto *labelCtrl = new wxStaticText(parent, wxID_STATIC, _(label), wxDefaultPosition, wxDefaultSize, 0);
```
Comment (sauravg) [inline src/ui/wxWidgets/wxUtilities.cpp:230]: Translations for label are done at the call sites

File: src/ui/wxWidgets/PasswordSafeFrame.cpp [hunk 3]
```diff
@@ -3145,7 +3145,7 @@ void PasswordSafeFrame::UpdateSelChanged(const CItemData *pci)
     if (dca == -1)
       dca = PWSprefs::GetInstance()->GetPref(PWSprefs::DoubleClickAction);
   }
-  m_statusBar->SetStatusText(_(PWSprefs::GetDCAdescription(dca)), StatusBar::Field::DOUBLECLICK);
```
Comment (sauravg) [inline src/ui/wxWidgets/PasswordSafeFrame.cpp:3148]: GetDCADescription() returns translated strings

File: Misc/rc2cpp.pl [hunk 4]
```diff
@@ -138,7 +138,7 @@ sub WriteHFile {
 #if !defined(_WIN32) || defined(__WX__)
 #include <map>
 #include "../os/typedefs.h" // for definition of TCHAR
-extern std::map<int, const TCHAR *> ${b}_st;
```
Comment (sauravg) [inline Misc/rc2cpp.pl:141]: wxTRANSLATE returns `char *`

File: Misc/rc2cpp.pl [hunk 5]
```diff
@@ -168,23 +168,24 @@ sub WriteCPPFile {
...
 using namespace std;
 
 namespace {
-  pair<int, const TCHAR *> Pairs[] = {
+  pair<int, const char *> Pairs[] = {
 PREAMBLE
 # print %MAP, sorted by constant name, just to be consistent
     my $key;
     foreach $key (sort keys %MAP) {
-        print CPP "    make_pair($key, _($MAP{$key})),\n";
```
Comment (sauravg) [inline Misc/rc2cpp.pl:181]: Strings in core_st.cpp are part of static variables, so they may not get translated with `_(...)`

See https://docs.wxwidgets.org/3.2/group__group__funcmacro__string.html#ga437ea6ba615b75dac8603e96ec864160

File: src/ui/wxWidgets/GridCtrl.cpp [hunk 6]
```diff
@@ -752,11 +752,11 @@ void GridCtrl::RearrangeItemsDateTimeBased(ItemsCollection& collection, int colu
       else if (dt.ParseDate(datetime, &end)) {
         collection.insert(std::pair<wxDateTime, const CItemData*>(dt, GetItem(row)));
         pws_os::Trace(L"Warning - Sorting may be incorrect for date string: %ls ; day: %d ; month: %d ; year: %d",
-          datetime.wc_str(), dt.GetDay(), dt.GetMonth(), dt.GetYear());
+          static_cast<const wchar_t*>(datetime.wc_str()), dt.GetDay(), dt.GetMonth(), dt.GetYear());
```
Comment (sauravg) [inline src/ui/wxWidgets/GridCtrl.cpp:755]: `wc_str()` may return a wraper object if `wx_USE_UNICODE_UTF8` is defined. Nothing to do with wx3.3 specifically

File: src/ui/wxWidgets/PWFiltersEditor.cpp [hunk 7]
```diff
@@ -85,40 +85,40 @@ const std::map<int, wxString> FieldTypeString = {
...
-  {FT_ENTRYTYPE, _("Entry type")},
-  {FT_ENTRYSTATUS, _("Entry status")},
-  {FT_UNKNOWNFIELDS, _("Unknown fields")},
-  {FT_PASSWORDLEN, _("Password Length")},
-  {HT_PRESENT, _("Field present")},
-  {HT_ACTIVE, _("Field active")},
-  {HT_NUM, _("Number stored")},
-  {HT_MAX, _("Maximal Number stored")},
-  {HT_CHANGEDATE, _("Change Date")},
-  {HT_PASSWORDS, _("Previous Passwords")},
```
Comment (sauravg) [inline src/ui/wxWidgets/PWFiltersEditor.cpp:98]: These are static strings, `_(...)` may not work for them.

File: src/ui/wxWidgets/PasswordSafeFrame.cpp [hunk 8]
```diff
@@ -859,7 +859,7 @@ void PasswordSafeFrame::AddLanguageMenu(wxMenu* parent)
   wxLanguage system_language = wxGetApp().GetSystemLanguage();
 
   for (auto &item : m_languages) {
-    wxString lang_name = _(get<1>(item.second));
+    wxString lang_name = wxGetTranslation(get<1>(item.second));
```
Comment (sauravg) [inline src/ui/wxWidgets/PasswordSafeFrame.cpp:862]: This may require the language string literals in ` PasswordSafeFrame::RegisterLanguageMenuItems()` to be wrapped in `wxTRANSLATE(...)`

```c++
- AddLanguage( ID_LANGUAGE_CHINESE,   wxLANGUAGE_CHINESE_SIMPLIFIED, L"Chinese"  );  /* code: 'zh_CN' */
+ AddLanguage( ID_LANGUAGE_CHINESE,   wxLANGUAGE_CHINESE_SIMPLIFIED, wxTRANSLATE("Chinese")  );  /* code: 'zh_CN' */

```

File: Misc/rc2cpp.pl [hunk 9]
```diff
@@ -168,23 +168,24 @@ sub WriteCPPFile {
 #define _(x) L ## x
```
Comment (dskrvk) [inline Misc/rc2cpp.pl:168]: No longer used.

File: Misc/rc2cpp.pl (hunk 4 above)
Comment (dskrvk) [reply Misc/rc2cpp.pl:141]: It’s a macro, it doesn’t return anything. I didn’t get why we need this change.

File: src/ui/wxWidgets/GridCtrl.cpp (hunk 6 above)
Comment (dskrvk) [reply src/ui/wxWidgets/GridCtrl.cpp:755]: Maybe use `tostringx(datetime)` instead?

File: src/ui/wxWidgets/PasswordSafeFrame.cpp (hunk 8 above)
Comment (dskrvk) [reply src/ui/wxWidgets/PasswordSafeFrame.cpp:862]: I think so too, though `_()` should suffice there since it's not a static context.

File: src/ui/wxWidgets/PWFiltersEditor.cpp [hunk 10]
```diff
@@ -369,11 +369,11 @@ wxSize pwFiltersFTChoiceRenderer::GetBestSize(wxGrid& WXUNUSED(grid), wxGridCell
   
     /* C++17 like
```
Comment (dskrvk) [inline src/ui/wxWidgets/PWFiltersEditor.cpp:370]: Nit: not sure what was the point of adding this comment, but given we're on C++20 now, we should either use the new syntax or delete the comment. As it is we're paying the cost of maintaining this commented-out code.

File: src/ui/wxWidgets/PasswordSafeFrame.cpp (hunk 8 above)
Comment (nobugshere) [reply src/ui/wxWidgets/PasswordSafeFrame.cpp:862]: Wouldn't you need _() here to expand to wxGetTranslation() ?

Comment (sauravg) [reply src/ui/wxWidgets/PasswordSafeFrame.cpp:862]: We're doing the translation explicitly above, in PasswordSafeFrame.cpp:862. So `_(...)` is not be required here.

Or we can use `_(...)` in `PasswordSafeFrame::RegisterLanguageMenuItems()` and remove the wxGetTranslation() call here.

But essentially, the names of the languages would display in English, unless we have translations for those, and we use `_(...)` or `wxTRANSLATE(...)` + `wxGetTranslation()`.

File: src/ui/wxWidgets/GridCtrl.cpp (hunk 6 above)
Comment (sauravg) [reply src/ui/wxWidgets/GridCtrl.cpp:755]: No point in paying the runtime cost of constructing a C++ object when it can be done at compile-time.

File: Misc/rc2cpp.pl (hunk 4 above)
Comment (sauravg) [reply Misc/rc2cpp.pl:141]: It translates to it's arg type, which is char *.

We can keep TCHAR & change `_(...)` to `_T(...)` in the perl script, but `_T(...)` & `wxT(...)` are now deprecated in wx

File: Misc/rc2cpp.pl (hunk 9 above)
Comment (sauravg) [reply Misc/rc2cpp.pl:168]: Oh, I missed this! So there was no translation happening for strings in core_st?

**Comment by ronys** [comment]
Hi,

From reading the comments, I can't decide if this is ready for merging or not. I'm converting this to 'draft'. When it's ready, please convert it back and I'll give it a final check and merge.

Thanks.

**Comment by sauravg** [comment]
@ronys It's not ready. Could you please add your thoughts on the implications of the changes in rc2cpp.pl, in particular the change that replaces `_(...)` with `wxTRANSLATE(...)`?

Before this PR, the `_(...)` was redfined in core_st.cpp to `L"..."`, so it wasn't being used for translations anyway, at least not how that macro is usually used for translations. I don't see how translations was working for those strings, unless xgettext works regardless of what macro we surround raw strings with. But the changes in this PR explicitly add translation for those strings. Is that the right thing to do? What am I missing here?

Also weigh in on whether we should retain TCHAR * in core_st map.

File: src/ui/wxWidgets/PasswordSafeFrame.cpp (hunk 8 above)
Comment (nobugshere) [reply src/ui/wxWidgets/PasswordSafeFrame.cpp:862]: Ah, I missed that.  I think "wxTRANSLATE(...) + wxGetTranslation()" is better; if the user changes the language the menu should be updated with the new translation.

File: Misc/rc2cpp.pl (hunk 9 above)
Comment (dskrvk) [reply Misc/rc2cpp.pl:168]: My understanding is previously this was done by `LoadAString`.

File: src/ui/wxWidgets/PasswordSafeFrame.cpp (hunk 8 above)
Comment (dskrvk) [reply src/ui/wxWidgets/PasswordSafeFrame.cpp:862]: Oh right, we don't want `_()` in `RegisterLanguageMenuItems` since it translates in place, not just marks for later translation.

File: Misc/rc2cpp.pl (hunk 4 above)
Comment (dskrvk) [reply Misc/rc2cpp.pl:141]: What you have now in the script + StringX.cpp looks fine - as long as the compiler is happy I think we can keep `char *`.

**Comment by ronys** [comment]
@sauravg - thanks for the clear summary.

As I understand it, `_()` is used by xgettext when scanning the source file, regardless of how it's defined, so that explains how it works in core_st.cpp

So in core_st.cpp I'd leave the _() in the code. As to its definition, it can be changed to 
`#define _(x) x`
along with replacing TCHAR with char and removing `#include "../os/typedefs.h" `

Finally, for clarity, I'd replace
`  s = _(core_st[id]).c_str();`
with
`  s = wxGetTranslation(core_st[id]).c_str();`
in line 159 of StringX.cpp
