### ISSUE TITLE
OSX 10.11 + wxWidgets 3.0.2 build does not work

### ISSUE THREAD

**Issue by neuralshock** [pwsafe/pwsafe#55]
Hi,

I can't build pwsafe on top of OSX 10.11 with wxWidgets 3.0.2.

First I had to patch the wxWidgets source with the changes in http://trac.wxwidgets.org/changeset/2a13ad64d85213846147c31f095e7b419487f677/git-wxWidgets to get it to build.

Trying to build pwsafe afterwards resulted in these errors in file.cpp:

```cpp
/Users/neuralshock/Repos/pwsafe/src/os/mac/file.cpp:374:7: error: redefinition of 'status'
  int status = ::stat(fn, &statbuf);
      ^
/Users/neuralshock/Repos/pwsafe/src/os/mac/file.cpp:370:7: note: previous definition is here
  int status;
      ^
/Users/neuralshock/Repos/pwsafe/src/os/mac/file.cpp:374:28: error: use of undeclared identifier 'statbuf'
  int status = ::stat(fn, &statbuf);
                           ^
2 errors generated.
```

I hacked file.cpp, based on other code in the file.

```cpp
bool pws_os::GetFileTimes(const stringT &filename,
			time_t &ctime, time_t &mtime, time_t &atime)
{
  struct stat info;
  struct stat statbuf;
  int status;
  size_t N = wcstombs(NULL, filename.c_str(), 0) + 1;
  char *fn = new char[N];
  wcstombs(fn, filename.c_str(), N);
  status = ::stat(fn, &statbuf);
```

The build progressed further, but failed again in about.cpp.

```cpp
/Users/neuralshock/Repos/pwsafe/src/ui/wxWidgets/about.cpp:195:28: error: use of undeclared identifier 'pwsafeAppName'
  const wxString vstring = pwsafeAppName + L" " + pwsafeVersionString;
                           ^
/Users/neuralshock/Repos/pwsafe/src/ui/wxWidgets/about.cpp:195:51: error: use of undeclared identifier 'pwsafeVersionString'
  const wxString vstring = pwsafeAppName + L" " + pwsafeVersionString;
                                                  ^
/Users/neuralshock/Repos/pwsafe/src/ui/wxWidgets/about.cpp:331:21: error: use of undeclared identifier 'MAJORVERSION'
    CheckVersion cv(MAJORVERSION, MINORVERSION, 0);
                    ^
/Users/neuralshock/Repos/pwsafe/src/ui/wxWidgets/about.cpp:331:35: error: use of undeclared identifier 'MINORVERSION'
    CheckVersion cv(MAJORVERSION, MINORVERSION, 0);
                                  ^
/Users/neuralshock/Repos/pwsafe/src/ui/wxWidgets/about.cpp:345:16: error: use of undeclared identifier 'pwsafeVersionString'
      newer += pwsafeVersionString + L"\n";
```

Update 12.01.2016:

Looks like the version.h file was empty (is this built somewhere?) so I copied the version.in file to version.h. Could something be wrong with the way I've tried to build it?

**Comment by jeffsf** [comment]
I can confirm the same problems under Mac OS X 10.11.2 and Xcode 7.2(7C68)

Pull request #65 addresses the problems with file.cpp

Still working through the issues with version.h 
* It is not generated by Xcode build
* There is a *Generate version.h* step showing
* The code for *Generate version.h* does not run from the command line as it is missing the parameters

    pwsafe/Xcode$ ../Misc/mkversion.pl ../src/ui/wxWidgets/version.in ../src/ui/wxWidgets/version.h
    Usage: ../Misc/mkversion.pl MAJOR=x MINOR=y [REV=z] [SPECIAL=w] template outfile

**Comment by jeffsf** [comment]
It looks like there are versions set in *Makefile.freebsd* and *Makefile.linux* but they are handled differently, as well as being different versions (0.96BETA and 0.98BETA respectively).

Suggest that there be a consistent place that the versions are defined.

It appears that the change that caused the Mac OS build to fail was around a8e81ccd where the parameters for MAJOR, MINOR, and SPECIAL were added to mkversion.pl

**Comment by ronys** [comment]
I'm in the process of moving the Linux builds to cmake, which might explain the version.in/h breakage.

Try the cmake approach to building and let me know what breaks:
$ cd pwsafe
$ mkdir build
$ cd build
$ cmake ..
$ make

**Comment by jeffsf** [comment]
Thanks for accepting the pull request for the *file.cpp* fix.

I'm not immediately able to get *cmake* to run on my Mac as GTest isn't installed:

pwsafe/build$ cmake ../
-- The CXX compiler identification is AppleClang 7.0.2.7000181
-- The C compiler identification is AppleClang 7.0.2.7000181
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at /usr/local/Cellar/cmake/3.4.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.4.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.4.2/share/cmake/Modules/FindGTest.cmake:204 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:24 (find_package)


-- Configuring incomplete, errors occurred!


Looking at *brew* for *gtest* gives the somewhat ominous 

pwsafe/build$ brew search gtest
Installing gtest system-wide is not recommended; it should be vendored
in your projects that use it.

See further https://github.com/google/googletest#Why_is_it_not_recommended_to_install_a_pre-compiled_copy_of_Goog

Looking into this further now

**Comment by kainjow** [comment]
Another project I watch uses gtest and last time I checked it failed to build on OS X.

If test requirements aren't too complicated, should consider switching to [Catch](https://github.com/philsquared/Catch), which is header only. I use it at my work across VS2013, VS2015, 10.7-10.11, Linux, FreeBSD, and no issues. Works great.

**Comment by neuralshock** [comment]
Have gone a bit further, without brew.

First I cloned the googletest repo and then inside the googletest/googletest folder:

```
$ cmake .
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/neuralshock/Repos/googletest/googletest
$ make
[ 50%] Built target gtest
[100%] Built target gtest_main
```

and this gives me the libgtest.a and libgtest_main.a files that are required.

Some env vars have to be declared for cmake to continue past the googletest requirements:

```
$ export | grep -i gtest
declare -x GTEST_INCLUDE_DIR="/Users/neuralshock/Repos/googletest/googletest/include/"
declare -x GTEST_INCLUDE_DIRS="/Users/neuralshock/Repos/googletest/googletest/include/"
declare -x GTEST_LIBRARY="/Users/neuralshock/Repos/googletest/googletest/libgtest.a"
declare -x GTEST_MAIN_LIBRARY="/Users/neuralshock/Repos/googletest/googletest/libgtest_main.a"
declare -x GTEST_ROOT="/Users/neuralshock/Repos/googletest/googletest/"
```

Now I find problems with wx :)

```
$ cmake ..
CMake Error at /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindwxWidgets.cmake:899 (find_package_handle_standard_args)
  CMakeLists.txt:29 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/neuralshock/Repos/pwsafe/build/CMakeFiles/CMakeOutput.log".

$ cmake ..
CMake Error at /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindwxWidgets.cmake:899 (find_package_handle_standard_args)
  CMakeLists.txt:29 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/neuralshock/Repos/pwsafe/build/CMakeFiles/CMakeOutput.log".
```

**Comment by yopito** [comment]
hello,
probably have to point where to find `wx-config` ?
On my side (VoidLinux), I had to patch `CMakeList.txt` this way: 
```
@@ -25,7 +25,7 @@
 
 if (NOT WIN32)
   # TODO - add support for wx build under Windows
-  set(wxWidgets_CONFIGURATION mswu)
+  set(wxWidgets_CONFIG_EXECUTABLE /usr/bin/wx-config-3.0)
   find_package(wxWidgets COMPONENTS adv base core html net REQUIRED)
   include(${wxWidgets_USE_FILE})
```

**Comment by yopito** [comment]
or adding its path to command-line:
```
cmake -D wxWidgets_CONFIG_EXECUTABLE=/path/to/wx-config .
```

**Comment by neuralshock** [comment]
Added path to cmd line, it worked!
Had to install Xerces as well, now hitting other issues because of version.h as mentioned above.

`
[ 55%] Building CXX object CMakeFiles/pwsafe.dir/src/ui/wxWidgets/guiinfo.cpp.o
[ 56%] Building CXX object CMakeFiles/pwsafe.dir/src/ui/wxWidgets/version.cpp.o
/Users/neuralshock/Repos/pwsafe/src/ui/wxWidgets/version.cpp:19:7: error: unknown type
      name 'wxString'
const wxString pwsafeAppName(APPNAME);
      ^
/Users/neuralshock/Repos/pwsafe/src/ui/wxWidgets/version.cpp:19:30: error: unknown
      type name 'APPNAME'
const wxString pwsafeAppName(APPNAME);
                             ^
/Users/neuralshock/Repos/pwsafe/src/ui/wxWidgets/version.cpp:21:7: error: unknown type
      name 'wxString'
const wxString pwsafeVersionString = wxString::Format(wxString(_T("v%d.%...
      ^
/Users/neuralshock/Repos/pwsafe/src/ui/wxWidgets/version.cpp:21:38: error: use of
      undeclared identifier 'wxString'
const wxString pwsafeVersionString = wxString::Format(wxString(_T("v%d.%...
                                     ^
/Users/neuralshock/Repos/pwsafe/src/ui/wxWidgets/version.cpp:21:64: error: use of
      undeclared identifier '_T'
const wxString pwsafeVersionString = wxString::Format(wxString(_T("v%d.%...
                                                               ^
/Users/neuralshock/Repos/pwsafe/src/ui/wxWidgets/version.cpp:22:55: error: use of
      undeclared identifier 'MAJORVERSION'
                                                      MAJORVERSION, MINO...
                                                      ^
/Users/neuralshock/Repos/pwsafe/src/ui/wxWidgets/version.cpp:22:69: error: use of
      undeclared identifier 'MINORVERSION'
                                                      MAJORVERSION, MINO...
                                                                    ^
/Users/neuralshock/Repos/pwsafe/src/ui/wxWidgets/version.cpp:23:58: error: use of
      undeclared identifier 'VCS_VERSION'
                                                      _T(VCS_VERSION), S...
                                                         ^
/Users/neuralshock/Repos/pwsafe/src/ui/wxWidgets/version.cpp:23:72: error: use of
      undeclared identifier 'SPECIALBUILD'
  ..._T(VCS_VERSION), SPECIALBUILD);
                      ^
9 errors generated.
make[2]: *** [CMakeFiles/pwsafe.dir/src/ui/wxWidgets/version.cpp.o] Error 1
make[1]: *** [CMakeFiles/pwsafe.dir/all] Error 2
make: *** [all] Error 2`

**Comment by ronys** [comment]
Thanks to all for working on this. Looking forward to a pull request for OSX support!

**Comment by neuralshock** [comment]
So, my fault in the previous error - I hacked about.cpp and completely forgot it.
After resetting the file to it's original state, I got this far:

`[ 77%] Building CXX object CMakeFiles/pwsafe.dir/src/ui/wxWidgets/SizeRestrictedPanel.cpp.o
[ 77%] Building CXX object CMakeFiles/pwsafe.dir/src/ui/wxWidgets/TimedTaskChain.cpp.o
[ 78%] Linking CXX executable pwsafe
ld: library not found for -luuid
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [pwsafe] Error 1
make[1]: *** [CMakeFiles/pwsafe.dir/all] Error 2
make: *** [all] Error 2
$ make
[ 36%] Built target core
[ 48%] Built target os
[ 50%] Linking CXX executable pwsafe
ld: library not found for -lXtst
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [pwsafe] Error 1
make[1]: *** [CMakeFiles/pwsafe.dir/all] Error 2
make: *** [all] Error 2`

libuuid can be installed via homebrew (ossp-uuid)
libXtst is (according to a page in Launchpad) "libxtst6: X11 Testing -- Record extension library"... can't find it in Homebrew.

**Comment by yopito** [comment]
Hint: switch from Homebrew to pkgsrc, probably more stuff available for MacOS ? At least libXtst ;)
see https://pkgsrc.joyent.com/install-on-osx/

**Comment by neuralshock** [comment]
I wouldn't want to - this brings X11 into the mix and so XQuartz is required.
I suppose the wx build was done without X11 since it supports Mac OS.

@ronys, is X11 needed for Mac builds?

**Comment by sauravg** [comment]
No, X11 is not required for Mac builds. Mac builds use Cocoa.

Is the XCode build working now?

**Comment by sauravg** [comment]
Please try the latest changes (16de764) in ronys's tree. That should fix the cmake builds on OSX, but the test binaries need more work. pwsafe can be built without xml and yubi like this (in the root checkout dir)

cmake -DNO_YUBI=ON -DNO_XML=ON .

The -D stuff should come before the path & there should be no space betwen -D and the option.

Tested with Xcode 6 on OSX 10.9

**Comment by neuralshock** [comment]
I'm not sure what I did some time ago with wxWindows, but it's not working anymore even with @yopito's suggestion. I can't find some of my notes... sorry for that.

So I installed wxmac via homebrew, and CMake finds wx-config properly.
cmake output:

``
$ cmake ..
$ cmake ..
-- The CXX compiler identification is AppleClang 7.3.0.7030029
-- The C compiler identification is AppleClang 7.3.0.7030029
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found GTest: /Users/<user>/Repos/googletest/googletest/libgtest.a  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found wxWidgets: -L/usr/local/lib;;;-framework IOKit;-framework Carbon;-framework Cocoa;-framework AudioToolbox;-framework System;-framework OpenGL;-lwx_osx_cocoau_adv-3.0;-lwx_baseu-3.0;-lwx_osx_cocoau_core-3.0;-lwx_osx_cocoau_html-3.0;-lwx_baseu_net-3.0 (found version "3.0.2") 
-- Looking for uuid/uuid.h
-- Looking for uuid/uuid.h - found
-- Looking for yk_init in ykpers-1
-- Looking for yk_init in ykpers-1 - not found
-- Yubikey support disabled
Gettext support not found, skipping I18N build
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/<user>/Repos/pwsafe/build
``

Build then fails during linking of 'coretest'

``
Scanning dependencies of target coretest
[ 84%] Building CXX object src/test/CMakeFiles/coretest.dir/AESTest.cpp.o
[ 84%] Building CXX object src/test/CMakeFiles/coretest.dir/FileV3Test.cpp.o
[ 85%] Building CXX object src/test/CMakeFiles/coretest.dir/ItemAttTest.cpp.o
[ 86%] Building CXX object src/test/CMakeFiles/coretest.dir/OSTest.cpp.o
[ 87%] Building CXX object src/test/CMakeFiles/coretest.dir/BlowFishTest.cpp.o
[ 87%] Building CXX object src/test/CMakeFiles/coretest.dir/FileV4Test.cpp.o
[ 88%] Building CXX object src/test/CMakeFiles/coretest.dir/ItemDataTest.cpp.o
[ 89%] Building CXX object src/test/CMakeFiles/coretest.dir/SHA256Test.cpp.o
[ 89%] Building CXX object src/test/CMakeFiles/coretest.dir/CommandsTest.cpp.o
[ 90%] Building CXX object src/test/CMakeFiles/coretest.dir/ItemFieldTest.cpp.o
[ 91%] Building CXX object src/test/CMakeFiles/coretest.dir/StringXTest.cpp.o
[ 91%] Building CXX object src/test/CMakeFiles/coretest.dir/coretest.cpp.o
[ 92%] Building CXX object src/test/CMakeFiles/coretest.dir/HMAC_SHA256Test.cpp.o
[ 93%] Building CXX object src/test/CMakeFiles/coretest.dir/KeyWrapTest.cpp.o
[ 93%] Building CXX object src/test/CMakeFiles/coretest.dir/TwoFishTest.cpp.o
[ 94%] Linking CXX executable coretest
Undefined symbols for architecture x86_64:
  "_CFBundleCopyBundleURL", referenced from:
      pws_os::getexecdir() in libos.a(dir.cpp.o)
  "_CFBundleCopyResourcesDirectoryURL", referenced from:
      GetBundleResourceDir() in libos.a(dir.cpp.o)
  "_CFBundleGetMainBundle", referenced from:
      pws_os::getexecdir() in libos.a(dir.cpp.o)
      GetBundleResourceDir() in libos.a(dir.cpp.o)
  "_CFRelease", referenced from:
      pws_os::getexecdir() in libos.a(dir.cpp.o)
      GetStringTFromURLRef(__CFURL const*) in libos.a(dir.cpp.o)
      GetBundleResourceDir() in libos.a(dir.cpp.o)
  "_CFStringGetBytes", referenced from:
      GetStringTFromURLRef(__CFURL const*) in libos.a(dir.cpp.o)
  "_CFStringGetLength", referenced from:
      GetStringTFromURLRef(__CFURL const*) in libos.a(dir.cpp.o)
  "_CFURLCopyAbsoluteURL", referenced from:
      GetBundleResourceDir() in libos.a(dir.cpp.o)
  "_CFURLCopyFileSystemPath", referenced from:
      GetStringTFromURLRef(__CFURL const*) in libos.a(dir.cpp.o)
  "_CFURLCreateCopyDeletingLastPathComponent", referenced from:
      pws_os::getexecdir() in libos.a(dir.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/test/coretest] Error 1
make[1]: *** [src/test/CMakeFiles/coretest.dir/all] Error 2
make: *** [all] Error 2
``

**Comment by sauravg** [comment]
This breakage is caused by 737a8f2, which was checked in 6 months ago.

I don't think it has anything to do with wxWidgets. The CoreFoundation libraries are not integrated with the build process of test binaries. I don't know enough about CMake right now to fix this.

**Comment by kainjow** [comment]
Probably just need something like this:

    if(APPLE)
        target_link_libraries(coretests "-framework CoreFoundation")
    endif()

or whatever the "coretests" target is called.

**Comment by neuralshock** [comment]
OK, looks like we have a build! 

![image](https://cloud.githubusercontent.com/assets/13039794/14833366/d6c8ea4a-0bf6-11e6-88ba-fad86ff015e9.png)

Thanks @kainjow - your suggestion was enough for me to modify src/test/CMakeLists.txt like so:

elseif (APPLE)
target_link_libraries(coretest ${GTEST_LIBRARIES} core os pthread "-framework CoreFoundation")
else ()

**Comment by kainjow** [comment]
Is the Xcode project still there? Last I checked, that built, so you could compare the bundle contents to find what's missing (maybe a resource?).

The icons are sourced from small images, and again last I checked the images can't be made smaller, so either you use a non-native toolbar or find a new set of icons.

**Comment by neuralshock** [comment]
Yes, it is; I had some problems with it as well.

The help files are built, I missed them - they're inside the build/help folder, I just had to copy them to the pwsafe binary's location.

![image](https://cloud.githubusercontent.com/assets/13039794/14835205/86f33336-0c00-11e6-84b9-761a2de8380a.png)

About the icons, a new set would be nicer than customizing the toolbar... but it works as it is :)

**Comment by JaquesBoum** [comment]
After following the Mac Build instructions and fiddling around with XCode for a while (tired eyed typo error...) I ended up at the same problems as OP.
Question to the more experienced builders: Should it build with XCode right now? And if not, is the CMake way described with the abovementioned change to src/test/CMakeLists.txt the current way to go?

**Comment by sauravg** [comment]
Yes, the xcode project should build. Follow the MAC_DEVELOPERS_README file.

**Comment by JaquesBoum** [comment]
Thanks for the quick reply, thats what I did (with a fresh clone). 
The build fails with the following errors:
`/Users/.../Documents/Code/pwsafe/src/ui/wxWidgets/about.cpp
/Users/.../Documents/Code/pwsafe/src/ui/wxWidgets/about.cpp:195:28: Use of undeclared identifier 'pwsafeAppName'
/Users/.../Documents/Code/pwsafe/src/ui/wxWidgets/about.cpp:195:51: Use of undeclared identifier 'pwsafeVersionString'
/Users/.../Documents/Code/pwsafe/src/ui/wxWidgets/about.cpp:331:35: C++ requires a type specifier for all declarations
/Users/.../Documents/Code/pwsafe/src/ui/wxWidgets/about.cpp:331:49: Unknown type name 'REVISION'
/Users/.../Documents/Code/pwsafe/src/ui/wxWidgets/about.cpp:345:16: Use of undeclared identifier 'pwsafeVersionString'`

**Comment by sauravg** [comment]
Which version of Xcode & OSX? Also, which .xcodeproj did you try to build?

I could build the latest master on OSX 10.9 with Xcode 6. Wasn�t a fresh clone, but still.

**Comment by JaquesBoum** [comment]
Maybe wasn't such a good choice of me to do a fresh install of everything last week :)
OSX 10.11.5 / XCode 7.3.1

I was using the File under /pwsafe/Xcode/pwsafe-xcode6.xcodeproj

**Comment by sauravg** [comment]
Ok. I could reproduce the problem. Had to clone afresh into a new directory.

Looking into it.

**Comment by sauravg** [comment]
This should be fixed with 8acd526, once the PR is merged in. After you pull those changes, make sure src/ui/wxWidgets/version.h is gone, and rebuild.

**Comment by ronys** [comment]
I'll close this ticket when someone confirms a successful OSX build.

**Comment by shpsec-david** [comment]
10.11.5 and Xcode 7.3.1, I've got a successful build with a fresh pull.

**Comment by ronys** [comment]
shpsec-david - thanks for the confirmation.

**Comment by JaquesBoum** [comment]
I can confirm successful build. Had to re-make WxWidgets first, then it went smoothly.
